import os
import pickle
import torch
import networkx as nx
import argparse
from tqdm import tqdm
from torch.nn.utils.rnn import pad_sequence
from collections import Counter

# Import unified model definition
from model import GPT, GPTConfig

def parse_generated_path(gen_text):
    """Parse the incremental path string generated by the model."""
    parts = gen_text.strip().split()
    if len(parts) < 2: return None, None, []
    try:
        source_node = int(parts[0])
        target_goal = int(parts[1])
        increments = []
        for p in parts[2:]:
            if p.startswith('inc_'):
                try:
                    increments.append(int(p.split('_')[1]))
                except:
                    continue
            elif p in ['\n', '[PAD]']:
                break
        return source_node, target_goal, increments
    except:
        return None, None, []

def validate_path(G, source, goal, increments):
    """Validate the generated path against graph topology."""
    if source is None: return 'invalid_format'
    current_node = source
    if not increments:
        return 'success' if source == goal else 'disconnected'
    for inc in increments:
        next_node = current_node + inc
        if not G.has_edge(current_node, next_node):
            return 'disconnected'
        current_node = next_node
        if current_node == goal: return 'success'
    return 'wrong_target'

@torch.no_grad()
def run_evaluation():
    parser = argparse.ArgumentParser(description="LSE-MTP Auto-checkpoint Evaluation")

    # Mode A: Automatic path construction (aligned with training script)
    parser.add_argument('--dataset', type=str, default='usg', help="er or usg")
    parser.add_argument('--num_nodes', type=int, default=100)
    parser.add_argument('--method', type=str, default='standard', choices=['standard', 'lse'])
    parser.add_argument('--n_tokens', type=int, default=1)
    parser.add_argument('--n_layer', type=int, default=6)
    parser.add_argument('--n_head', type=int, default=6)
    parser.add_argument('--n_embd', type=int, default=120)
    parser.add_argument('--ckpt_iter', type=str, default='final', help="'final' or specific iteration like '5000'")

    # Mode B: Manual checkpoint path (highest priority)
    parser.add_argument('--checkpoint', type=str, default='', help="Manual path to .pt file")

    # Inference config
    parser.add_argument('--batch_size', type=int, default=100)
    parser.add_argument('--temperature', type=float, default=0.8)
    parser.add_argument('--device', type=str, default='cuda')
    args = parser.parse_args()

    # 1. Determine Checkpoint Path
    if args.checkpoint:
        ckpt_path = args.checkpoint
    else:
        method_prefix = "lse_" if args.method == 'lse' else ""
        out_dir = f'out/{method_prefix}{args.dataset}_{args.n_layer}_{args.n_head}_{args.n_embd}_{args.num_nodes}_{args.n_tokens}t'

        if args.ckpt_iter == 'final':
            ckpt_path = os.path.join(out_dir, 'final_model.pt')
        else:
            ckpt_path = os.path.join(out_dir, f'ckpt_{args.ckpt_iter}.pt')

    if not os.path.exists(ckpt_path):
        raise FileNotFoundError(f"Checkpoint not found: {ckpt_path}\nPlease check parameters or training status.")

    # 2. Determine Data Directory
    data_dir = f"data/{args.dataset}_{args.num_nodes}"

    # 3. Load Resources
    print(f"Loading data from: {data_dir}")
    with open(os.path.join(data_dir, 'meta_incremental.pkl'), 'rb') as f:
        meta = pickle.load(f)
    stoi, itos = meta['stoi'], meta['itos']

    G = nx.read_graphml(os.path.join(data_dir, 'graph.graphml'))
    G = nx.relabel_nodes(G, {n: int(n) for n in G.nodes()})

    # 4. Load Model
    print(f"Loading checkpoint: {ckpt_path}")
    ckpt = torch.load(ckpt_path, map_location=args.device)
    conf = GPTConfig(**ckpt['model_args'])
    model = GPT(conf)

    sd = ckpt['model']
    if any(k.startswith('_orig_mod.') for k in sd.keys()):
        sd = {k.replace('_orig_mod.', ''): v for k, v in sd.items()}
    model.load_state_dict(sd)
    model.to(args.device).eval()

    # 5. Read Validation Set
    test_file = os.path.join(data_dir, 'val_incremental.txt')
    with open(test_file, 'r') as f:
        test_lines = [l.strip() for l in f.readlines() if l.strip()]

    # 6. Run Inference
    error_stats = Counter()
    encode = lambda s: [stoi[c] for c in s.split() if c in stoi]
    decode = lambda tokens: " ".join([itos[t] for t in tokens if t in itos])

    print(f"Starting evaluation on {len(test_lines)} cases...")
    for i in tqdm(range(0, len(test_lines), args.batch_size)):
        batch_lines = test_lines[i: i + args.batch_size]
        prompts, target_goals = [], []

        for line in batch_lines:
            parts = line.split()
            prompts.append(torch.tensor(encode(f"{parts[0]} {parts[1]}"), dtype=torch.long))
            target_goals.append(int(parts[1]))

        x = pad_sequence(prompts, batch_first=True, padding_value=0).to(args.device)
        y_batch = model.generate(x, max_new_tokens=meta['block_size'], temperature=args.temperature)

        for j, y_row in enumerate(y_batch.tolist()):
            gen_text = decode(y_row).split('\n')[0]
            src_out, _, incs = parse_generated_path(gen_text)
            result = validate_path(G, src_out, target_goals[j], incs)
            error_stats[result] += 1

    # 7. Summary Report
    total = sum(error_stats.values())
    success = error_stats['success']
    disconnected = error_stats['disconnected']
    wrong_target = error_stats['wrong_target']
    invalid = error_stats['invalid_format']

    print("\n" + "=" * 50)
    print(f"REPORT FOR: {os.path.basename(ckpt_path)}")
    print("-" * 50)
    print(f"Total Test Samples:  {total}")
    print(f"Success Rate:        {(success / total) * 100:>6.2f}%  ({success})")
    print(f"Disconnected Rate:   {(disconnected / total) * 100:>6.2f}%  ({disconnected})")
    print(f"Wrong Target Rate:   {(wrong_target / total) * 100:>6.2f}%  ({wrong_target})")
    print(f"Invalid Format Rate: {(invalid / total) * 100:>6.2f}%  ({invalid})")
    print("=" * 50)

if __name__ == "__main__":
    run_evaluation()